### ISSUE TITLE
Error printing in console, not sure if it's doing anything

### ISSUE THREAD

**Issue by BitSents** [ps-dps/KeepSomeInventory#14]
The error logged in the console goes as follows, not sure if it is impacting the datapack by any means.

```
[16:05:58] [ServerMain/ERROR]: Failed to load function ps-keep:on_death
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 81: ...s-keep:all<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Expected whitespace to end one argument, but found trailing data at position 81: ...s-keep:all<--[HERE]
        at ib.a(SourceFile:80) ~[server-1.20.6.jar:?]
        at alt.a(SourceFile:83) ~[server-1.20.6.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```

**Comment by PuckiSilver** [comment]
What minecraft version are you trying to run it in? The pack has not been updated to 1.20.5 or 1.20.6 yet, the newest version it currently works in is 1.20.4

**Comment by PuckiSilver** [comment]
If you don’t provide further information, I will close this shortly due to getting stale without any progress.

**Comment by BitSents** [comment]
Sorry, totally forgot to hit send.
I'm running it on 1.20.6, even though I knew it wouldn't probably work too well. Any plans for updating the data pack?

**Comment by PuckiSilver** [comment]
I will most likely update the data pack to the new versions, yes - can’t give a time estimate right now though

**Comment by PuckiSilver** [comment]
I updated the data pack to 1.20.5+, please re-open if any issues persist 👌 
https://modrinth.com/datapack/keep-some-inventory/version/v1.4.0
